### ISSUE TITLE
Login cookie integration

### ISSUE THREAD

**Issue by kevindeyne** [medusa-ui/hydra#142]
You should be able to log into Hydra (/login) (as much as possible with standard Spring Security) and have an authentication success handler trigger. The handler should set a serverside cookie with a JWT token:

https://github.com/medusa-ui/hydra/blob/862b6b9fccf9bd5cb0e81cfdd103c8520f28f316/hydra-core/src/main/java/io/getmedusa/hydra/security/controller/LoginController.java#L62-L66

This serverside cookie will then be sent along with any subsequent request. On the Medusa side we should interpret it (see https://github.com/medusa-ui/medusa/blob/main/medusa-ui/src/main/java/io/getmedusa/medusa/core/filters/JWTTokenInterpreter.java) and use that to log us in.

My current problem is that I can't seem to get the success handler to trigger for logins.

Attempts: 
- [JWTAuthSuccessHandler](https://github.com/medusa-ui/hydra/blob/rewrite-1.0.0/hydra/src/main/java/io/getmedusa/hydra/core/config/JWTAuthSuccessHandler.java)
- [HydraAuthenticationSuccessHandler](https://github.com/medusa-ui/hydra/blob/rewrite-1.0.0/hydra/src/main/java/io/getmedusa/hydra/core/config/HydraAuthenticationSuccessHandler.java)

**Comment by dirkdeyne** [comment]
> My current problem is that I can't seem to get the success handler to trigger for logins.

The standard way to add a SuccessHandler like [JWTAuthSuccessHandler](https://github.com/medusa-ui/hydra/blob/rewrite-1.0.0/hydra/src/main/java/io/getmedusa/hydra/core/config/JWTAuthSuccessHandler.java) is via SecurityConfig [SecurityWebFilterChain  bean](https://github.com/medusa-ui/hydra/blob/rewrite-1.0.0/hydra/src/main/java/io/getmedusa/hydra/core/config/SecurityConfig.java#L35)
```java
@Order(Ordered.HIGHEST_PRECEDENCE)
@Bean
 public SecurityWebFilterChain springSecurityFilterChain(ServerHttpSecurity http, JWTAuthSuccessHandler jwtAuthSuccessHandler) {
   return http
       .authorizeExchange()
      .anyExchange().permitAll()
      .and()
      .formLogin(form -> form.authenticationSuccessHandler(jwtAuthSuccessHandler)) // <-- add successhandler
      .csrf().disable() //TODO except for login!
      .build();
}
```

_Remark:_ Authentication holds the HydraUser as [Principal](https://github.com/medusa-ui/hydra/blob/rewrite-1.0.0/hydra/src/main/java/io/getmedusa/hydra/core/config/JWTAuthSuccessHandler.java#L39); so use `authentication.getPrincipal()` instead of `authentication.getDetails()`

**Comment by kevindeyne** [comment]
Oof, thanks. I've been struggling with this for two days and somehow could not find it. I've verified this approach works!
